[package]
name = "jules"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.23", features = ["derive", "cargo"] }
lalrpop-util = { version = "0.20.0", features = ["lexer"] }
regex = "1"

[build-dependencies]
lalrpop = "0.20.0"
